name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
    - name: Docker login
      env: 
        DOCKER_USER: adarye
        DOCKER_PASSWORD: dckr_pat_opgtFr5ZBfZO_MSwCTC5onw37Zg
      run: |
        echo "logging"
        docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
        echo "logged"
    #- name: Build the Docker image
      #run: docker build . --file Dockerfile --tag my-image-name:$(date +%s)
